;;-*-coding: utf-8;-*-
(define-abbrev-table 'LaTeX-mode-abbrev-table
  '(
    ("0" "$0$" nil :count 0)
    ("1" "$1$" nil :count 0)
    ("2" "$2$" nil :count 0)
    ("3" "$3$" nil :count 0)
    ("4" "$4$" nil :count 2)
    ("5" "$5$" nil :count 1)
    ("6" "$6$" nil :count 0)
    ("7" "$7$" nil :count 0)
    ("8" "$8$" nil :count 0)
    ("9" "$9$" nil :count 1)
    ("A" "$A$" nil :count 5)
    ("B" "$B$" nil :count 1)
    ("C" "$C$" nil :count 1)
    ("D" "$D$" nil :count 0)
    ("E" "$E$" nil :count 1)
    ("F" "$F$" nil :count 0)
    ("G" "$G$" nil :count 0)
    ("H" "$H$" nil :count 0)
    ("I" "$I$" nil :count 0)
    ("J" "$J$" nil :count 0)
    ("K" "$K$" nil :count 0)
    ("L" "$L$" nil :count 0)
    ("M" "$M$" nil :count 0)
    ("N" "$N$" nil :count 0)
    ("O" "$O$" nil :count 0)
    ("P" "$P$" nil :count 0)
    ("Q" "$Q$" nil :count 0)
    ("R" "$R$" nil :count 0)
    ("S" "$S$" nil :count 0)
    ("T" "$T$" nil :count 0)
    ("U" "$U$" nil :count 0)
    ("V" "$V$" nil :count 0)
    ("W" "$W$" nil :count 0)
    ("X" "$X$" nil :count 3)
    ("Y" "$Y$" nil :count 1)
    ("Z" "$Z$" nil :count 5)
    ("assoc" "associative" nil :count 0)
    ("b" "$b$" nil :count 0)
    ("c" "$c$" nil :count 0)
    ("comm" "commutative" nil :count 0)
    ("cts" "continuous" nil :count 0)
    ("d" "$d$" nil :count 0)
    ("e" "$e$" nil :count 2)
    ("f" "$f$" nil :count 0)
    ("fn" "function" nil :count 0)
    ("g" "$g$" nil :count 0)
    ("h" "$h$" nil :count 0)
    ("i" "$i$" nil :count 0)
    ("j" "$j$" nil :count 0)
    ("k" "$k$" nil :count 0)
    ("l" "$l$" nil :count 0)
    ("m" "$m$" nil :count 1)
    ("n" "$n$" nil :count 1)
    ("o" "$o$" nil :count 0)
    ("p" "$p$" nil :count 0)
    ("q" "$q$" nil :count 0)
    ("r" "$r$" nil :count 0)
    ("s" "$s$" nil :count 0)
    ("t" "$t$" nil :count 1)
    ("u" "$u$" nil :count 0)
    ("v" "$v$" nil :count 0)
    ("w" "$w$" nil :count 0)
    ("x" "$x$" nil :count 0)
    ("y" "$y$" nil :count 0)
    ("z" "$z$" nil :count 0)
   ))

(define-abbrev-table 'lean4-abbrev-table
  '(
    ("and" "∧" nil :count 1)
    ("arr" "#[" nil :count 0)
    ("ax" "axiom" nil :count 0)
    ("cdot" "·" nil :count 0)
    ("ch" "#check" nil :count 0)
    ("df" ":=" nil :count 1)
    ("ev" "#eval" nil :count 0)
    ("ex" "example" nil :count 0)
    ("ftor" "<$>" nil :count 0)
    ("im" "=>" nil :count 0)
    ("lar" "←" nil :count 3)
    ("not" "¬" nil :count 2)
    ("or" "∨" nil :count 1)
    ("prnt" "#print" nil :count 0)
    ("rd" "reduce" nil :count 0)
    ("str" "String" nil :count 0)
    ("th" "theorem" nil :count 0)
    ("to" "→" nil :count 2)
   ))

