#+title: GNU Emacs configuration
#+author: Ronald Huidrom
#+email: ronhuidrom@gmail.com
#+language: en

** Knot Emacs

#+BEGIN_QUOTE
This is my Emacs customization, prioritized for speed, efficiency and functionality.
#+END_QUOTE

+ Builds on vanilla GNU Emacs. Assumes GNU Emacs 30.1 or higher.
+ Uses use-package and use-package-vc. I have tried straight.el in the past and I believe use-package-vc (built-in) is cleaner, leaner and makes Emacs boot up faster.
+ Native compilation is enabled by default. Native compilation cuts down boot up time and Emacs starts faster overall.
+ Using server-client model, Emacs starts up almost instantly.
+ I use my version of Colemak-DH keyboard layout but my config would work fine in QWERTY or other layouts as well. This is due to Emacs's mnemonic-keybindings design.

*** Design philosophy

I want an editor and personal companion for life. Minimalist, fast, extensible and stable. Accomplish more by using less. Don't keep things you don't need. When there is a choice, choose the built-in way: they are more stable and predictable. When you want some feature, first try to write it in ~Emacs Lisp~ yourself. Be brief. Implement only what you need. Keep it light and do things the native way.

A minimalist modeline, a super lightweight but feel-good startup screen and a nice looking lightweight theme... what more visual effects do you need?

*** My usecase

I use Emacs for editing text, writing documents, proving theorems, doing mathematics, programming, creating presentations, managing files, organizing my life and more. In each of these usecases, I haven't found anything that does it better than Emacs does.

*** On the editor

To make editing more efficient and faster, I have redefined or reimplemented some of the built-in functions and added new ones. I shall add new ones (when I find myself needing one and not for the sake of just adding). Most are built from built-in functions and some extra juice (of course). One emphasis is to overload commands and make them context-sensitive, so that they behave as expected. Universal arguments can and must be exploited whenever it's convenient.

*** Over the years

I began my Emacs journey with vanilla keybindings. Over the years, I tried ~evil-mode~, to find out what the craze was all about, and even started liking modal editing, but due to some limitations and personal desire for more quests, I tried ~meow~ modal editing, even found it much better than ~evil~ but finally after a long affair with modal editing, I came back to good old, chordy, musical, rhythmic vanilla keys. In the long run, I realized that vanilla keybindings are just better. Although modal editing does have its benefits, I found that a pure emacsy editing is just more efficient, predictable, and leaner overall.

I believe that one of the greatest things about Emacs is its infinite extensibility and one should not compromise that.

*** Other things

- To enable Emacs keybindings for all GTK text fields (including Firefox), run in shell:

#+BEGIN_SRC bash
gsettings set org.gnome.desktop.interface gtk-key-theme "Emacs"
#+END_SRC

** Early Init

Emacs loads ~early-init.el~ file before ~init.el~. This following marks the start of the ~early-init.el~ file.

#+BEGIN_SRC emacs-lisp :tangle "early-init.el"
;;; early-init.el --- Load this before init.el -*- lexical-binding: t; -*-
#+END_SRC

*** Defer garbage collection

Garbage collection is important but may slow down Emacs startup slightly. The following defers garbage collection to speed up startup.

#+BEGIN_SRC emacs-lisp :tangle "early-init.el"
;; Defer garbage collection
(setq gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 0.6)
#+END_SRC

*** Set ~default-frame-alist~

It's important to set ~default-frame-alist~ early as this affects the how the Emacs frames start and look like. Here, we set the font to ~Iosevka~, sized 15. We start Emacs in fullscreen, maximized.

#+BEGIN_SRC emacs-lisp :tangle "early-init.el"
(setq default-frame-alist '((font . "Iosevka Term-15") (fullscreen . maximized)))
#+END_SRC

*** Disable UI elements

By default, Emacs starts with lots of UI baggage. They could be helpful to a complete beginner or someone coming from GUI apps that uses menu bars, tool bars and things like that. We won't have those baggage here. Period.

#+BEGIN_SRC emacs-lisp :tangle "early-init.el"
;; Disable UI elements
(menu-bar-mode   -1)
(tool-bar-mode   -1)
(scroll-bar-mode -1)
(tooltip-mode    -1)
(set-fringe-mode -1)
#+END_SRC

*** Inhibit startup annoyances

By default, Emacs also pulls in lots of extra baggage at startup. To get a cleaner startup, we inhibit a lot of theses baggage.

+ Setting ~inhibit-startup-screen~ to ~t~ inhibits the default ~Welcome to GNU Emacs~ startup screen. Now Emacs will start with the ~*scratch*~ buffer.
+ To not load ~default.el~ from the Emacs installation directory, we set ~inhibit-default-init~ to ~t~.
+ Setting ~inhibit-x-resources~ to ~t~ inhibits loading X resources.
+ Setting ~frame-inhibit-implied-resize~ to ~t~ stops Emacs from automatically resizing frame when changing font or UI elements.
+ Setting ~server-client-instructions~ to ~nil~ makes client sessions cleaner.
+ Setting ~emacs-start-time~ to ~current-time~ records the time Emacs started, for profiling startup time later.
+ Setting ~warning-minimum-level~ to ~error~ inhibits auto pop ups of warning buffer unless it's an error. The value could be ~emergency~ (Emacs warns you only when there is an emergency).
+ The line ~(fset 'display-startup-echo-area-message #'ignore)~ suppresses the echo area message shown at startup.

#+BEGIN_SRC emacs-lisp :tangle "early-init.el"
;; Inhibit startup annoyances
(setq
 inhibit-startup-screen  t
 inhibit-default-init    t
 inhibit-startup-message t
 inhibit-x-resources     t
 inhibit-compacting-font-caches t
 inhibit-startup-echo-area-message t
 frame-inhibit-implied-resize t
 server-client-instructions nil
 emacs-start-time (current-time)
 warning-minimum-level :error)

(fset 'display-startup-echo-area-message #'ignore)
#+END_SRC

*** Native compilation tweaks

In newer versions of Emacs, native compilation is on by default. The following code make some adjustments to how Emacs native compiles the source files.

#+BEGIN_SRC emacs-lisp :tangle "early-init.el"
;; Native compilation tweaks
(setq package-native-compile t
      package-install-upgrade-built-in t
      native-comp-deferred-compilation t
      native-comp-warning-on-missing-source nil
      native-comp-async-report-warnings-errors nil
      native-comp-speed 3
      native-comp-defer t)
#+END_SRC

Then we end the ~early-init.el~ file with the following file.

#+BEGIN_SRC emacs-lisp :tangle "early-init.el"
(provide 'early-init)
#+END_SRC

** The ~init~ file
