#+title: GNU Emacs configuration
#+author: Ronald Huidrom
#+email: ronhuidrom@gmail.com
#+language: en

** My extensions

#+BEGIN_QUOTE
This is my Emacs customization, prioritized for speed, efficiency and functionality.
#+END_QUOTE

*** Some custom functions
**** ~rh/act-inside~

The command ~rh/act-inside~ (bound to ~M-i~) kills the content of the balanced expression that contains the point and put the point inside (think of Vim's change-inner but not having to type so long to specify the delimiter)

Suppose the current point is denoted by ~|~ and we have

#+BEGIN_SRC emacs-lisp
(here is a "nice| string" inside)
#+END_SRC

Pressing ~M-i~ takes us to

#+BEGIN_SRC emacs-lisp
(here is a "" inside)
#+END_SRC

However, ~C-M-u M-i~ would have taken us to

#+BEGIN_SRC emacs-lisp
(|)
#+END_SRC

The command ~rh/act-inside~ accepts universal argument. For instance, ~C-u M-i~ copies the content of the balanced expression instead of killing it.

**** ~rh/change-inside-forward~

The command ~rh/change-inside-forward~ (bound to ~M-I~) does the same as ~rh/act-inside~ but for the next balanced expression. Suppose we have

#+BEGIN_SRC emacs-lisp
the fruits |are "apple", "mango" and "guava"
#+END_SRC

Then pressing ~M-I~ takes us to

#+BEGIN_SRC emacs-lisp
the fruits are "|", "mango" and "guava"
#+END_SRC

To jump several balanced expressions ahead, we supply prefix argument. For instance, typing a fruit (say, banana) and pressing ~C-2 M-I~ takes us to

#+BEGIN_SRC emacs-lisp
the fruits are "banana", "mango" and "|"
#+END_SRC

To jump back, we supply negative argument. For instance, typing another fruit (say, papaya) and pressing ~C-u -2 M-I~ takes us to

#+BEGIN_SRC emacs-lisp
the fruits are "|", "mango" and "papaya"
#+END_SRC

**** ~rh/copy-sexp-at-or-around-point~

In my config, this command is bound to ~C-M-w~ (by default, Emacs binds ~append-next-kill~ to this key, which I have rebound to ~C-M-S-w~). This commands checks if the point is at the start of a balanced expression. If it is, then the expression is copied. Otherwise, it copies the smallest balanced expression that contains the current point.

Invoking ~C-M-w~, in the following case, copies the whole string.

#+BEGIN_SRC emacs-lisp
"The GNU/Linux opera|ting system."
#+END_SRC

Prefix argument is supplied to specify how many balanced expressions to copy. For instance, invoking ~C-3 C-M-w~, in the following case, copies all the three strings.

#+BEGIN_SRC emacs-lisp
"G|NU" "Emacs" "thermonuclear editor"
#+END_SRC

**** ~rh/forward-opening-delimiter~



*** Other things

- To enable Emacs keybindings for all GTK text fields (including Firefox), run in shell:

#+BEGIN_SRC bash
gsettings set org.gnome.desktop.interface gtk-key-theme "Emacs"
#+END_SRC

** Early Init

Emacs loads ~early-init.el~ file before ~init.el~. This following marks the start of the ~early-init.el~ file.

#+BEGIN_SRC emacs-lisp :tangle "early-init.el"
;;; early-init.el --- Load this before init.el -*- lexical-binding: t; -*-
#+END_SRC

*** Defer garbage collection

Garbage collection is important but may slow down Emacs startup slightly. The following defers garbage collection to speed up startup.

#+BEGIN_SRC emacs-lisp :tangle "early-init.el"
;; Defer garbage collection
(setq gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 0.6)
#+END_SRC

*** Set ~default-frame-alist~

It's important to set ~default-frame-alist~ early as this affects the how the Emacs frames start and look like. Here, we set the font to ~Iosevka~, sized 15. We start Emacs in fullscreen, maximized.

#+BEGIN_SRC emacs-lisp :tangle "early-init.el"
(setq default-frame-alist '((font . "Iosevka Term-15") (fullscreen . maximized)))
#+END_SRC

*** Disable UI elements

By default, Emacs starts with several GUI elements (menu bar, tool bar, scroll bar). These are unnecessary and look polluting in a minimalist setup.

#+BEGIN_SRC emacs-lisp :tangle "early-init.el"
;; Disable UI elements
(menu-bar-mode   -1)
(tool-bar-mode   -1)
(scroll-bar-mode -1)
(tooltip-mode    -1)
(set-fringe-mode -1)
#+END_SRC

*** Inhibit startup annoyances

By default, Emacs also pulls in lots of extra baggage at startup. To get a cleaner startup, we inhibit a lot of theses baggage.

+ Setting ~inhibit-startup-screen~ to ~t~ inhibits the default ~Welcome to GNU Emacs~ startup screen. Now Emacs will start with the ~*scratch*~ buffer.
+ To not load ~default.el~ from the Emacs installation directory, we set ~inhibit-default-init~ to ~t~.
+ Setting ~inhibit-x-resources~ to ~t~ inhibits loading X resources.
+ Setting ~frame-inhibit-implied-resize~ to ~t~ stops Emacs from automatically resizing frame when changing font or UI elements.
+ Setting ~server-client-instructions~ to ~nil~ makes client sessions cleaner.
+ Setting ~emacs-start-time~ to ~current-time~ records the time Emacs started, for profiling startup time later.
+ Setting ~warning-minimum-level~ to ~error~ inhibits auto pop ups of warning buffer unless it's an error. The value could be ~emergency~ (Emacs warns you only when there is an emergency).
+ The line ~(fset 'display-startup-echo-area-message #'ignore)~ suppresses the echo area message shown at startup.

#+BEGIN_SRC emacs-lisp :tangle "early-init.el"
;; Inhibit startup annoyances
(setq
 inhibit-startup-screen  t
 inhibit-default-init    t
 inhibit-startup-message t
 inhibit-x-resources     t
 inhibit-compacting-font-caches t
 inhibit-startup-echo-area-message t
 frame-inhibit-implied-resize t
 server-client-instructions nil
 emacs-start-time (current-time)
 warning-minimum-level :error)

(fset 'display-startup-echo-area-message #'ignore)
#+END_SRC

*** Native compilation tweaks

In newer versions of Emacs, native compilation is on by default. The following code make some adjustments to how Emacs native compiles the source files.

#+BEGIN_SRC emacs-lisp :tangle "early-init.el"
;; Native compilation tweaks
(setq package-native-compile t
      package-install-upgrade-built-in t
      native-comp-deferred-compilation t
      native-comp-warning-on-missing-source nil
      native-comp-async-report-warnings-errors nil
      native-comp-speed 3
      native-comp-defer t)
#+END_SRC

Then we end the ~early-init.el~ file with the following file.

#+BEGIN_SRC emacs-lisp
(provide 'early-init)
#+END_SRC

** The ~init~ file

** Final gc restoration?

#+BEGIN_SRC emacs-lisp
(add-hook 'emacs-startup-hook
          (lambda ()
            (setq gc-cons-threshold (* 1024 1024 32)
                  gc-cons-percentage 0.1)))
#+END_SRC
