#!/bin/bash
set -e

source ~/scripts/lib/functions.sh
source ~/scripts/lib/colors.sh

# Directories to clean
dirs=(
    "$HOME/"
    "/usr/local/bin/"
)

print "${BLUE}Cleaning Emacs backup and autosaves...${NC}"

for dir in "${dirs[@]}"; do
  print "${BLUE}Checking ${NC}$dir..."
  print "${YELLOW}Removing...${NC}"
  
  # Delete backup files (*~)
  find "$dir" -type f -name '*~' -print -delete

  # Delete auto-save files (#file#)
  find "$dir" -type f -name '#*#' -print -delete
done

print "${BLUE}Cleanup complete.${NC}"
